2019-11-29 Fri 07:17:36 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:17:49 log.py log_response 228 - ERROR - Internal Server Error: /LAMProcessData/test/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py", line 1534, in test
    return render(re, 'test.html')
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "D:\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Python37\lib\site-packages\django\template\context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "D:\Python37\lib\site-packages\django\template\context_processors.py", line 40, in debug
    if settings.DEBUG and request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS:
AttributeError: module 're' has no attribute 'META'
2019-11-29 Fri 07:17:50 log.py log_response 228 - WARNING - Not Found: /favicon.ico
2019-11-29 Fri 07:19:27 log.py log_response 228 - ERROR - Internal Server Error: /LAMProcessData/test/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py", line 1534, in test
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "D:\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Python37\lib\site-packages\django\template\context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "D:\Python37\lib\site-packages\django\template\context_processors.py", line 40, in debug
    if settings.DEBUG and request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS:
AttributeError: module 're' has no attribute 'META'
2019-11-29 Fri 07:19:31 log.py log_response 228 - ERROR - Internal Server Error: /LAMProcessData/test/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py", line 1534, in test
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "D:\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Python37\lib\site-packages\django\template\context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "D:\Python37\lib\site-packages\django\template\context_processors.py", line 40, in debug
    if settings.DEBUG and request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS:
AttributeError: module 're' has no attribute 'META'
2019-11-29 Fri 07:19:47 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:20:20 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:20:22 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:20:24 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:20:27 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:20:35 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:20:39 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:22:32 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:22:36 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:24:17 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:24:20 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 07:25:00 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 07:25:03 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:36:55 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:37:07 log.py log_response 228 - WARNING - Not Found: /favicon.ico
2019-11-29 Fri 20:37:20 log.py log_response 228 - WARNING - Not Found: /favicon.ico
2019-11-29 Fri 20:38:23 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:38:25 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:38:33 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:38:37 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:38:44 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:38:49 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:38:58 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:39:19 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:39:21 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:39:36 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:39:38 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:39:45 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:41:53 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py changed, reloading.
2019-11-29 Fri 20:41:57 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:42:04 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:44:17 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\models.py changed, reloading.
2019-11-29 Fri 20:44:20 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
2019-11-29 Fri 20:45:25 autoreload.py trigger_reload 203 - INFO - E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\models.py changed, reloading.
2019-11-29 Fri 20:45:28 autoreload.py run_with_reloader 578 - INFO - Watching for file changes with StatReloader
