2019-12-24 20:19:56,629 - run_with_reloader - 578 - INFO - Watching for file changes with StatReloader
2019-12-24 20:19:57,494 - <module> - 55 - DEBUG - SendBefore_NotRecive : [<CNCProcessStatus: CNCProcessStatus object (2038721)>]
2019-12-24 20:19:57,498 - <module> - 56 - DEBUG - Waitfor_Recive : [2038721]
2019-12-24 20:20:01,534 - log_response - 228 - WARNING - Not Found: /favicon.ico
2019-12-24 20:20:03,600 - log_response - 228 - WARNING - Not Found: /favicon.ico
2019-12-24 20:20:57,221 - log_response - 228 - ERROR - Internal Server Error: /LAMProcessData/ProcessRecords/WorksectionOperate_by_id/1/tab-panel.html/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\1.chenbo\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\views.py", line 2364, in lamprocess_worksection_operate
    _worksection = Worksection.objects.get(id = WorksectionID)
  File "D:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python37\lib\site-packages\django\db\models\query.py", line 399, in get
    clone = self.filter(*args, **kwargs)
  File "D:\Python37\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python37\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python37\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Python37\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Python37\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Python37\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Python37\lib\site-packages\django\db\models\lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "D:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1/tab-panel.html'
