2020-02-29 00:45:30,181 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 00:45:30,788 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 00:45:31,361 - log_response - 228 - ERROR - Internal Server Error: /LAMProcessData/QueryData/AnalyseLAMProcess_LayerData/
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\query_views.py", line 746, in queryData_Analysedata_LayerData_By_MissionIDList
    in _missionID_list]
  File "E:\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\query_views.py", line 745, in <listcomp>
    _product_code_list = ['%s (id:%s)' % (LAMProcessMission.objects.get(id=int(id)).LAM_product.product_code, id) for id
ValueError: invalid literal for int() with base 10: ''
2020-02-29 00:45:35,804 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:43:49,058 - _main_loop - 579 - DEBUG - Looking for jobs to run
2020-02-29 01:43:49,068 - _run_jobs - 69 - DEBUG - Started worker thread
2020-02-29 01:43:49,068 - _run_job - 496 - WARNING - Run time of job "OpenLog (trigger: cron[hour='0'], next run at: 2020-02-29 00:00:00)" was missed by 1:43:49.068912
2020-02-29 01:43:49,069 - _main_loop - 588 - DEBUG - Next wakeup is due at 2020-02-29 19:20:34.595375 (in 63405.536920 seconds)
2020-02-29 01:43:50,069 - _run_jobs - 94 - DEBUG - Exiting worker thread
2020-02-29 01:47:36,484 - log_response - 228 - ERROR - Internal Server Error: /LAMProcessData/QueryData/AnalyseLAMProcess_LayerData/
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\query_views.py", line 746, in queryData_Analysedata_LayerData_By_MissionIDList
    in _missionID_list]
  File "E:\1-program\11-LAMDataServer\lamdataserver\LAMProcessData\query_views.py", line 745, in <listcomp>
    _product_code_list = ['%s (id:%s)' % (LAMProcessMission.objects.get(id=int(id)).LAM_product.product_code, id) for id
ValueError: invalid literal for int() with base 10: ''
2020-02-29 01:47:40,187 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:40,790 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:41,395 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:42,007 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:42,622 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:43,223 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:43,838 - log_response - 228 - WARNING - Not Found: /favicon.ico
2020-02-29 01:47:44,443 - log_response - 228 - WARNING - Not Found: /favicon.ico
